### ISSUE TITLE
Warnings about changes to tidyr syntax for (un)nest()

### ISSUE THREAD

**Issue by Lisark45** [nacnudus/ukfarm#1]
Thank you so much for your worked examples.

However, an error's produced running the R script in;
[ukfarm](https://github.com/nacnudus/ukfarm)/defra-stats-foodfarm-landuselivestock-june-results-nationalparks-16jan18/

Error: Problem with `mutate()` column `data`.
i `data = map(data, tidy_sheet)`.

Can you amend please?

**Comment by nacnudus** [comment]
Thanks for reporting the problem, which was that the tidyr package's syntax has changed.  In https://github.com/nacnudus/ukfarm/commit/470879120fd2a655eaea731321a6a05f1792b564 I have fixed all the other files.  Please open a new issue if you find one that I have missed (or any other problems).

**Comment by Lisark45** [comment]
Thank you so much, much appreciated.
